### ISSUE TITLE
Pull timers not displaying for DBM users

### ISSUE THREAD

**Issue by javedbartlett** [BigWigsMods/BigWigs#1351] opened 2023-02-17 12:57 UTC
## Describe the problem
Pull timers are not showing for DBM users - only Bigwigs users

### What steps will reproduce the problem?

1.  /pull 10
2.  observe the pull timer display for bigwigs users, but not DBM users

### What version of BigWigs are you using? (Stating 'latest' is not useful)
266.1

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
Used the countdown timer in various M+ dungeons before inserting the keystone and DBM members did not see it, whereas Bigwigs members did. This happened to 6-7 different DBM users.

**Comment by sir-wilhelm** [comment] 2023-02-17 15:59
I noticed the same thing this week. I went back to using `/cd 10` to get the countdown started for everyone, but then we don't get the bar.

**Comment by ntowle** [comment] 2023-02-17 17:50
Are your DBM users all up to date? DBM changed how they send and receive addon messages in their most recent versions in response to a Blizzard change.

See:
- https://github.com/BigWigsMods/BigWigs/issues/1350
- https://github.com/DeadlyBossMods/DBM-Retail/issues/859

**Comment by funkydude** [comment] 2023-02-17 19:56
Cannot reproduce this. Just tested with a BigWigs and DBM user, both saw each other's pull timers just fine. So you're probably not on the latest version. Type /bw and show a screenshot of what version it shows.

**Comment by javedbartlett** [comment] 2023-02-19 09:23
> Cannot reproduce this. Just tested with a BigWigs and DBM user, both saw each other's pull timers just fine. So you're probably not on the latest version. Type /bw and show a screenshot of what version it shows.

Update: My raid lead is using DBM and some bigwigs users couldn't see their timer - I could see the timer though.

![image](https://user-images.githubusercontent.com/48427864/219939709-0fe95362-207b-4e2f-85fe-a313e7cbead4.png)

**Comment by funkydude** [comment] 2023-02-20 20:47
Closing this. The solution is making sure your raid members are up to date with both addons.

**Closed by funkydude** 2023-02-20 20:47 UTC
Labels: retail
