### ISSUE TITLE
Disable nameplate icons

### ISSUE THREAD

**Issue by morgan35543** [BigWigsMods/BigWigs#1823] opened 2024-09-14 17:18 UTC
## Describe the problem

What is the reasoning behind these nameplate icons? I use bigwigs for timers, and plater for nameplates. Why do I now have bigwigs icons on my nameplates with no option to just turn them off? (Going through every single ability one by one is, frankly, ridiculous.

**Comment by funkydude** [comment] 2024-09-14 17:20
Duplicate of #1784

**Closed** 2024-09-14 17:20 UTC
Labels: retail
