### ISSUE TITLE
Timer on Nameplate icon

### ISSUE THREAD

**Issue by blecaplol** [BigWigsMods/BigWigs#1853] opened 2024-09-27 04:04 UTC
1st give us option to disabled it completely. not on by default
2nd i usually let omnicc control my  timer when i disabled yours omnicc is not detecting it im not sure if this issue should be address to u or omnicc author

**Comment by funkydude** [comment] 2024-09-27 04:10
Duplicate of #1784
There's no need to support OmniCC because you can replicate the exact same settings as OmniCC within the BigWigs settings.

**Closed by funkydude** 2024-09-27 04:10 UTC
Labels: retail

**Comment by blecaplol** [comment] 2024-09-28 16:44
omnicc has color coded timer.

**Comment by Justw8** [comment] 2024-09-28 16:45
Change the font color.

**Comment by funkydude** [comment] 2024-09-28 17:56
If you're talking about color that changes when it's less than 3 seconds left on the timer, I recommend you change the glow setting to make it glow earlier. This is a better way to achieve an early warning than the font color.
