### ISSUE TITLE
Script ran too long

### ISSUE THREAD

**Issue by Duffroxwow** [BigWigsMods/BigWigs#333] opened 2017-07-26 23:03 UTC
Message: Interface\AddOns\BigWigs\Loader.lua:181: script ran too long
Time: 07/26/17 20:01:08
Count: 1
Stack: Interface\AddOns\BigWigs\Loader.lua:181: script ran too longInterface\SharedXML\SharedBasicControls.lua:189: in function <Interface\SharedXML\SharedBasicControls.lua:187>
Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `LoadAddOn'
Interface\AddOns\BigWigs\Loader.lua:181: in function <Interface\AddOns\BigWigs\Loader.lua:169>
Interface\AddOns\BigWigs\Loader.lua:205: in function <Interface\AddOns\BigWigs\Loader.lua:204>
Interface\AddOns\BigWigs\Loader.lua:1051: in function `?'
Interface\AddOns\BigWigs\Loader.lua:748: in function <Interface\AddOns\BigWigs\Loader.lua:747>

Locals: errorTypeCVar = "scriptErrors"
warnType = false
msg = "Interface\AddOns\BigWigs\Loader.lua:181: script ran too long"
messageType = 0
hideErrorFrame = false
IsErrorCVarEnabled = <function> defined @Interface\SharedXML\SharedBasicControls.lua:183

**Comment by funkydude** [comment] 2017-07-26 23:05
Duplicate of #284

**Closed** 2017-07-26 23:05 UTC

**Comment by Citizen-alpha** [comment] 2020-03-06 13:05
I am having a similar issue. This is the error log I am getting. 
3x BigWigs\Loader.lua:322: script ran too long
[string "@BigWigs\Loader.lua"]:322: in function <BigWigs\Loader.lua:308>
[string "@BigWigs\Loader.lua"]:333: in function <BigWigs\Loader.lua:328>
[string "@BigWigs\Loader.lua"]:345: in function <BigWigs\Loader.lua:343>
[string "@BigWigs\Loader.lua"]:1291: in function `?'
[string "@BigWigs\Loader.lua"]:1027: in function <BigWigs\Loader.lua:1026>

Locals:
obj = nil
index = 68
loaded = true
reason = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @ElvUI\Modules\actionbars\Bind.lua:331
(*temporary) = <table> {
 DisableBlizzard = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:741
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 MainMenuMicroButton_SetNormal = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:93
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 handledBars = <table> {
 }
 PositionAndSizeBar = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:122
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 LAB_ChargeCreated = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:1114
 RawHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:395
 SetupMicroBar = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:192
 ActivateBindMode = <function> defined @ElvUI\Modules\actionbars\Bind.lua:37
 Button_OnEnter = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:680
 RemoveBindings = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:450
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MicroHeight = 30.000043
 UpdateButtonConfig = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:891
 UpdateMicroBarVisibility = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:115
 defaultModuleState = true
 Tooltip_OnUpdate = <function> defined @ElvUI\Modules\actionbars\Bind.lua:297
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 handledbuttons = <table> {
 }
 UpdatePetBindings = <function> defined @ElvUI\Modules\actionbars\PetBar.lua:263
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 Extra_SetAlpha = <function> defined @ElvUI\Modules\actionbars\ExtraAB.lua:20
 Initialized = true
 CreateBarPet = <function> defined @ElvUI\Modules\actionbars\PetBar.lua:276
 PositionAndSizeBarShapeShift = <function> defined @ElvUI\Modules\actionbars\StanceBar.lua:107
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 baseName = "ElvUI"
 LAB_ButtonCreated = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:1131
 hooks = <table> {
 }
 UpdateMicroButtons = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:179
 fadeParent = Elv_ABFade {
 }
 UpdateMicroButtonsParent = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:101
 db = <table> {
 }
 HandleMicroButton = <function> defined @ElvUI\Modules\actionbars\MicroBar.lua:56
 Initialize = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:1161
 LAB_ButtonUpdate = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:1137
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Bar_OnLeave = <function> defined @ElvUI\Modules\actionbars\ActionBars.lua:670
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 RegisterMacro = <function> defined @ElvUI\Modules\actionbars\Bind.lua:331
 LAB_MouseUp = <function> defined @ElvUI\Modules\
