### ISSUE TITLE
Nameplate icons

### ISSUE THREAD

**Issue by joerithienpont** [BigWigsMods/BigWigs#1898] opened 2024-11-15 14:29 UTC
What a moronic change to add nameplate icons without a way to disable the function. Why would you implement this without an opt-in????
And no, I'm going to do 100 clicks to find every single ability that is activated by default.
Took me hours to find which WA or plater script did this. Just to find bigwigs wanted to be a nameplater addon all of a sudden....

**Comment by Justw8** [comment] 2024-11-15 14:54
duplicate of https://github.com/BigWigsMods/BigWigs/issues/1784

You gave yourself the solution. Another is to uninstall.
BigWigs is not a nameplate addon: we don't modify your nameplates.
We do show cooldowns of abilities on enemies in dungeons and raids.

**Closed by Justw8** 2024-11-15 14:54 UTC
Labels: retail
