### ISSUE TITLE
[classic] SFK error

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#717] opened 2019-09-26 09:09 UTC
### What steps will reproduce the problem?  
1.  Happened in SFK, in Commander Springvale's room. Before he was pulled.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v3

### Do you have an error log of what happened?
![i_view32_oDowqdWd1G](https://user-images.githubusercontent.com/21211868/65675174-12439280-e04e-11e9-8396-94de443755e8.png)

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment] 2019-10-08 14:17
Duplicate of https://github.com/BigWigsMods/LittleWigs/issues/484

**Closed by funkydude** 2019-10-08 14:17 UTC
