### ISSUE TITLE
Lua Error...

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs#1429] opened 2023-08-07 22:21 UTC
## Describe the problem

1x BigWigs/Loader.lua:1110: script ran too long
[string "@BigWigs/Loader.lua"]:1110: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2933: in function `PlaySound'
[string "@LittleWigs/Dragonflight/Neltharus/Trash.lua"]:313: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:610: in function <BigWigs_Core/BossPrototype.lua:576>

Locals:
self = <table> {
 MendingClay = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:321
 VolcanicGuard = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:231
 ReverberatingSlam = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:413
 BlazingSlash = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:239
 MoteOfCombustion = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:346
 sayCountdowns = <table> {
 }
 enableMobs = <table> {
 }
 BindingSpearApplied = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:266
 ImbuedMagmaApplied = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:286
 enabled = true
 optionHeaders = <table> {
 }
 MoteOfCombustionApplied = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:354
 MoltenArmy = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:470
 MoltenBarrier = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:459
 SendMessage = <function> defined @BigWigs/Loader.lua:1106
 ConflagrantBattery = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:394
 name = "BigWigs_Bosses_Neltharus Trash"
 ExplosiveConcoction = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:430
 localization = <table> {
 }
 MoltenBarrierRemoved = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:465
 BurningRoar = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:274
 BlazingDetonation = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:423
 DragonboneAxe = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:365
 ScorchingBreath = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:333
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:1092
 soundOptions = <table> {
 }
 colorOptions = <table> {
 }
 ThrowExperimentalConcoction = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:213
 MoltenCore = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:437
 OverseerLaharDeath = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:293
 db = <table> {
 }
 GOSSIP_SHOW = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:197
 CandescentTempest = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:452
 MagmaConflagration = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:442
 MagmaFist = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:302
 toggleOptions = <table> {
 }
 OnBossEnable = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:125
 EruptiveCrush = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:280
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 ThrowLava = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:382
 IrontorchCommanderDeath = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:406
 displayName = "Trash"
 ScorchingFusillade = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:400
 BindingSpear = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:256
 BurningChainPickedUp = <function> defined @LittleWigs/Dragonflight/Neltharus/Trash.lua:224
 instanceId = 2519
 RegisterMessage = <function> defined @BigWigs/Loader.lua:1071
 moduleName = "Neltharus Trash"
 UnregisterEvent = <function> defined @BigWigs_Core/Core.lua:71
 toggleDefaults = <table> {
 }
}
msg = "BigWigs_Voice"
(for generator) = <function> d

### What steps will reproduce the problem?

1.  dont know was in a middle of running M+
2.  
3.

**Comment by funkydude** [comment] 2023-08-08 08:27
This is the 4th time you're opening an issue about the exact same thing.
For reference here is your previous issue where you stated "remove my cc i dont need this anymore"

Duplicate of https://github.com/BigWigsMods/LittleWigs/issues/882

**Closed by funkydude** 2023-08-08 08:27 UTC
Labels: retail

**Comment by Milky063** [comment] 2023-08-08 14:39
no idea, i get a lua error and i post. then if you want to fix it then its all you. good luck👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
