### ISSUE TITLE
Add option to replace bar text

### ISSUE THREAD

**Issue by ZeeD26** [BigWigsMods/BigWigs#477] opened 2018-04-02 08:55 UTC
It would be nice if we could manually decide which text is shown for certain bars.

This would allow the user to do things similarly to what you implemented for the Eye of Azshara boss "Lady Hatecoil" with her Static Nova ability, i.e., giving a hint about what to do.

**Comment by funkydude** [comment] 2018-04-02 17:54
Duplicate of #140.

**Closed by funkydude** 2018-04-02 17:54 UTC
