### ISSUE TITLE
Request: Add a function switch  option of nameplate cooldown

### ISSUE THREAD

**Issue by CrisReus** [BigWigsMods/BigWigs#1861] opened 2024-09-28 16:40 UTC
plz, this is very important to me.
I had used WA.
I hope my plater keep clean.
thx!

**Comment by funkydude** [comment] 2024-09-28 18:00
We have no idea what you're asking for.

**Comment by Verzhul** [comment] 2024-09-28 21:33
Hey,
I'm pretty sure he wants (as do I) the option to just turn off the cooldowns of spells shown on enemy nameplates (see screenshot for reference).
![nameplates cooldowns](https://github.com/user-attachments/assets/76183dad-ad82-4d5b-ad2b-7e37e98cf0c4)

Currently we are forced to go into the options of every trash mob and every dungeon to remove this which can take a while.
Would be nice to remove this with a single click instead.


Thanks for your hard work! Bye!

**Comment by funkydude** [comment] 2024-09-28 21:37
@Verzhul do not hijack other people's posts with assumptions. And do a search prior to posting #1784

**Comment by Verzhul** [comment] 2024-09-28 22:11
lol I just wanted to help. I mentioned that this seems to be already covered. holy hell. Worse than at work. Ban me away.

**Comment by CrisReus** [comment] 2024-09-29 04:15
enable/disable nameplate cooldown

**Comment by funkydude** [comment] 2024-09-29 04:17
Duplicate of #1784

**Closed by funkydude** 2024-09-29 04:17 UTC
Labels: retail
