### ISSUE TITLE
CVar EnableErrorSpeech always being set to True

### ISSUE THREAD

**Issue by Bowbee** [BigWigsMods/BigWigs#1273] opened 2022-10-04 07:56 UTC
## Describe the problem
(Updated with new findings, see first comment).
The CVar `Sound_EnableErrorSpeech` is always being set to 1 as per [BossBlock.lua:274](https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/BossBlock.lua#L274) after the user has set this off in Blizz audio settings.

### What steps will reproduce the problem?

1.  Enable error speech, enable `disableErrorSpeech` in BossBlock plugin.
2.  Disable error speech in Blizz UI. Reload UI to save.
3.  Open bigwigs via /bigwigs and it will set cvar to 1, as if a DC was detected.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v249.4 (65e7a32 sha)

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)

Have confirmed the culprit is line 274 of BossBlock.lua. This only happens if error speech has been disabled manually after enabling "Mute error speech".

Tested this with just BigWigs enabled on a fresh character.

Thank you :)

**Comment by Bowbee** [comment] 2022-10-04 08:16
After some further testing, it seems this behaviour can only occur when error speech is disabled manually via BlizzUI after `self.db.profile.disableErrorSpeech` has already been set to true.

The option to mute error speech is correctly unable to be selected in BossBlock UI.
If mute error speech is enabled, it is assumed the player wants error speech enabled by default - and so this is correct behaviour.

Leaving thread open for discussion for the case of: "Player wants to disable error speech" - can we hook into changes to the CVar and detect disable, and disable `self.db.profile.disableErrorSpeech` too?

**Comment by funkydude** [comment] 2022-10-22 20:07
Closing this as it's intended behavior. Further discussion on alerting the user is in PR mentioned above.

**Closed by funkydude** 2022-10-22 20:07 UTC
Labels: retail
