### ISSUE TITLE
Bar error after spec swap

### ISSUE THREAD

**Issue by Malcanthet** [BigWigsMods/BigWigs#24] opened 2016-09-08 06:49 UTC
### What version of BigWigs are you using?

 Latest download from curse v8

Using ElvUI, AddOn Skins and BigWigs and Little Wigs.

Since Legion launch I've had the following issue: first I get the first error,
it doesn't appear straight away, sometimes it would work for a dungeon or two. I checked the BigWigs bar settings font size, time and text align had all been made blank, as I fixed them all it would pop up with a new error, when I'd put in the numbers again it came up with the second lua error I'm posting. Disabling AddOn Skins skinning fixes the issue so I've done so for now. I deleted the previous settings as well from WTF folder and re-did things, still came up with the errors.

First Error:

Message: Interface\AddOns\BigWigs_Plugins\Bars.lua:1468: Usage: <unnamed>:SetJustifyH("justify")
Time: 09/07/16 10:40:29
Count: 1
Stack: [C](?): ?
[C](?): in function `SetJustifyH'
Interface\AddOns\BigWigs_Plugins\Bars.lua:1468: in function`?'
Interface\AddOns\BigWigs\Loader.lua:637: in function `SendMessage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:1422: in function`Bar'
...Ons\LittleWigs\Legion\AssaultOnVioletHold\Betrug.lua:43: in function `OnEngage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:707: in function`Engage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:530: in function `?'
Interface\AddOns\BigWigs_Core\Core.lua:52: in function <Interface\AddOns\BigWigs_Core\Core.lua:47>

Locals:

After setting all bar settings again:

Interface\AddOns\BigWigs_Plugins\Bars.lua:882: attempt to compare number with nil
Time: 09/07/16 10:47:10
Count: 1
Stack: (tail call): ?
Interface\AddOns\BigWigs_Plugins\Bars.lua:882: in function <Interface\AddOns\BigWigs_Plugins\Bars.lua:881>
[C](?): in function `sort'
Interface\AddOns\BigWigs_Plugins\Bars.lua:900: in function <Interface\AddOns\BigWigs_Plugins\Bars.lua:885>
Interface\AddOns\BigWigs_Plugins\Bars.lua:1499: in function`?'
Interface\AddOns\BigWigs\Loader.lua:637: in function `SendMessage'
Interface\AddOns\BigWigs_Core\Core.lua:258: in function`Test'
Interface\AddOns\BigWigs_Options\Options.lua:83: in function <Interface\AddOns\BigWigs_Options\Options.lua:82>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?

[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...ace\AddOns\AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...kins\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:28: in function <...kins\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:25>

Locals: <none>

If you need any more information just ask.

**Comment by Malcanthet** [comment] 2016-09-08 09:57
Edit: I spoke to soon, popped up today again, this time it started when I entered Vault of the Wardens, was fine in Maw of Souls and Neltharion's lair before that.

**Comment by funkydude** [comment] 2016-09-09 01:28
That line number is incorrect, are you actually using the latest version? v8 as of typing this.

**Comment by Malcanthet** [comment] 2016-09-09 05:26
Just checked, it has a value, what seems to happen is on some encounters it seems to reset itself. Then when I leave a dungeon it comes back and it is fine. Last night it happened on mythic VH on the first boss enounter, after we switched to mythic Maw of Souls and it was fine for the entire instance. I then entered mythic Vaut of the Wardens and it didn't work for the first and last boss but the rest seemed fine. It seems so random, I have no idea what cause could be.

**Comment by funkydude** [comment] 2016-09-09 10:14
Does it happen if you only have BigWigs enabled?

**Comment by Malcanthet** [comment] 2016-09-12 20:56
No idea, would require some testing, have only had issue once over the past few days, it was when someone created a pull timer bar and I didn't get a bar and the align reset, not sure if that's relevant but will mention it. Will get back to you on the other bit once I get a chance to test without anything else.

**Comment by Malcanthet** [comment] 2016-09-16 06:23
Using v9.

I had no issues for a bit so decided to test with no add ons for a while, no problems. Put all add ons in again and I've had one issue so far. It was on the 2nd boss in heroic Neltharion's lair (Ularogg iirc). What seemed to happen once I closely inspected all settings was that the scale was set to blank for the regular bars and also the two align options (a side effect of the scale being blank perhaps?). What also seems to happen when it happens is it shows me Big Wigs messages still and also the default Blizzard boss emotes (normally turned off).

Let me know if there's anything I can do to help narrow down why this happens.

**Comment by Malcanthet** [comment] 2016-09-16 06:23
I should add I've ran heroic and mythic Neltharion's lair after without incident.

**Comment by funkydude** [comment] 2016-09-16 07:25
All I can assume is one of your addons is messing with your settings. Please do a search for `BigWigs` in all Lua files in your addons folder.

**Comment by funkydude** [comment] 2016-09-21 00:02
Did you find anything?

**Comment by Malcanthet** [comment] 2016-09-21 04:14
I was just going to write you. I wanted to runt with it for a few days to see if any issues would crop up that could put a light on the problem. I'd not had any issues for a few days then yesterday I had it come up twice. Once before first boss in mythic HoV. I relogged after boss and it fixed itself. The second time was at first boss in mythic Vault of the Wardens when leader created a pull timer.

The only addon I can think of that directly tinkers with settings is AddOnSkins and I have the BigWigs skinning option disabled in there. I don't think any other addons I use would affect it. Here is a list:
- ElvUI
- AddOnSkins
- Clique
- Postal
- LittleWigs
- BigWigs
- Weak Auras

**Comment by funkydude** [comment] 2016-09-21 09:21
A list of addons isn't of much use. For all I know, it could be caused by one of your WeakAura strings. You'll need to use a program like Notepad++ and search for `BigWigs` in your WoW folder and check what files it finds hits in.

**Comment by Malcanthet** [comment] 2016-09-21 09:30
I just thought I'd list them in case there were any conflicts I didn't know about that you did. Not a problem, already have notepad++. Is it the WTF files you want me to check? I did already (I should've mentioned that in hindsight, early morning, pre coffee brain doesn't function too well) and it doesn't come up with anything unless in ElvUI for the addonskins part and those are set to false.

**Comment by funkydude** [comment] 2016-09-21 09:32
Both the `WTF` folder (WeakAura strings) and the `Interface` folder (addons) would be a good idea.

**Comment by Malcanthet** [comment] 2016-09-21 09:38
Rechecked the WTF files, nothing there. Will check the addons folder as well, will take longer so wil lget back to yuo once I'm done.

**Comment by Malcanthet** [comment] 2016-09-21 09:49
In the Weak auras prototypes.lua there are refrences to Big Wigs, starts at line 1871
`-- BigWigs
  ["BigWigs Message"] = {
    type = "event",
    events = {
      "BigWigs_Message"
    },
    name = L["BigWigs Message"],
    init = function(trigger)
      WeakAuras.RegisterBigWigsCallback("BigWigs_Message");
      local ret = "local use_cloneId = %s;"
      return ret:format(trigger.use_cloneId and "true" or "false");
    end,
    statesParameter = "all",
    canHaveAuto = true,
    args = {
      {
        name = "addon",
        init = "arg",
        display = L["BigWigs Addon"],
        type = "string"
      },
      {
        name = "spellId",
        init = "arg",
        display = L["Spell Id"],
        type = "number",
        store = true
      },
      {
        name = "text",
        init = "arg",
        display = L["Message"],
        type = "longstring",
        store = true
      },
      {
        name = "name",
        init = "text",
        hidden = true,
        test = "true",
        store = true
      },
      {}, -- Importance, might be useful
      {
        name = "icon",
        init = "arg",
        hidden = true,
        test = "true",
        store = true
      },
      {
        name = "cloneId",
        display = L["Clone per Event"],
        type = "toggle",
        test = "true",
        init = "use_cloneId and WeakAuras.GetUniqueCloneId() or ''"
      },
    }
  },
  ["BigWigs Timer"] = {
    type = "status",
    events = {
      "BigWigs_StartBar", "BigWigs_StopBar", "BigWigs_Timer_Update",
    },
    force_events = "BigWigs_Timer_Force",
    name = L["BigWigs Timer"],
    canHaveAuto = true,
    canHaveDuration = true,
    triggerFunction = function(trigger)
      WeakAuras.RegisterBigWigsTimer();
      local ret = [[
        return function(states, event, id)
        local triggerAddon = %s;
        local triggerSpellId = %s;
        local triggerText = %s;
        local triggerTextOperator = "%s";
      ]]

      ret = ret:format(trigger.use_addon and ('"' .. (trigger.addon or '') .. '"') or "nil",
                       trigger.use_spellId and tostring(trigger.spellId) or "nil",
                       trigger.use_text and ('"' .. (trigger.text or '') .. '"') or "nil",
                       trigger.use_text and trigger.text_operator or ""
                       );

      local copyOrSchedule;
      if (trigger.use_remaining) then
        local ret2 = [[
          local remainingCheck = %s;
        ]];
        ret = ret .. ret2:format(trigger.remaining or 0);
        copyOrSchedule = [[
          local remainingTime = bar.expirationTime - GetTime()
          if (remainingTime %s %s) then
            WeakAuras.CopyBigWigsTimerToState(bar, states, id);
          elseif (states[id] and states[id].show) then
              states[id].show = false;
              states[id].changed = true;
          end
          if (remainingTime >= remainingCheck) then
            WeakAuras.ScheduleBigWigsCheck(bar.expirationTime - remainingCheck);
          end
          ]]
        copyOrSchedule = copyOrSchedule:format(trigger.remaining_operator or "", trigger.remaining or 0);
      else
        copyOrSchedule = [[
          WeakAuras.CopyBigWigsTimerToState(bar, states, id);
          ]];
      end

      if (trigger.use_cloneId) then
        ret = ret .. [[
          if (event == "BigWigs_StartBar") then
            if (WeakAuras.BigWigsTimerMatches(id, triggerAddon, triggerSpellId, triggerTextOperator, triggerText)) then
              local bar = WeakAuras.GetBigWigsTimerById(id);
          ]]
        ret = ret .. copyOrSchedule;
        ret = ret .. [[
            end
          elseif (event == "BigWigs_StopBar") then
            if (states[id]) then
              states[id].show = false;
              states[id].changed = true;
            end
          elseif (event == "BigWigs_Timer_Update") then
            for id, bar in pairs(WeakAuras.GetAllBigWigsTimers()) do
              if (WeakAuras.BigWigsTimerMatches(id, triggerAddon, triggerSpellId, triggerTextOperator, triggerText)) then
                ]]
        ret = ret .. copyOrSchedule;
        ret = ret .. [[
              end
            end
          elseif (event == "BigWigs_Timer_Force") then
            wipe(states);
            for id, bar in pairs(WeakAuras.GetAllBigWigsTimers()) do
              if (WeakAuras.BigWigsTimerMatches(id, triggerAddon, triggerSpellId, triggerTextOperator, triggerText)) then
                ]]
        ret = ret .. copyOrSchedule;
        ret = ret .. [[
              end
            end
          end
          return true;
        end
        ]]
        return ret;
      else
        ret = ret .. [[
          local bar = WeakAuras.GetBigWigsTimer(triggerAddon, triggerSpellId, triggerTextOperator, triggerText);
          local id = "";
          if (bar) then
        ]]
        ret = ret .. copyOrSchedule;
        ret = ret .. [[
          else
            if (states[""] and states[""].show) then
              states[""].show = false;
              states[""].changed = true;
            end
          end
          return true;
        end]]
        --print(ret);
        return ret;
      end
    end,
    statesParameter = "full",
    canHaveAuto = true,
    args = {
      {
        name = "addon",
        display = L["BigWigs Addon"],
        type = "string",
      },
      {
        name = "spellId",
        display = L["Spell Id"], -- Correct?
        type = "number",
      },
      {
        name = "text",
        display = L["Message"],
        type = "longstring",
      },
      {
        name = "remaining",
        display = L["Remaining Time"],
        type = "number",
      },
      {
        name = "cloneId",
        display = L["Clone per Event"],
        type = "toggle",
        test = "true",
        init = "use_cloneId and WeakAuras.GetUniqueCloneId() or ''"
      }
    },
    automaticrequired = true,
  },`

**Comment by Malcanthet** [comment] 2016-09-21 09:55
In Weak Auras Generic Trigger.lua, starts at line 1770:

```
-- BigWigs
do
  local registeredBigWigsEvents = {}
  local bars = {};
  local nextExpire; -- time of next expiring timer
  local recheckTimer; -- handle of timer

  local function recheckTimers()
    local now = GetTime();
    nextExpire = nil;
    for id, bar in pairs(bars) do
      if (bar.expirationTime < now) then
        bars[id] = nil;
        WeakAuras.ScanEvents("BigWigs_StopBar", id);
      elseif (nextExpire == nil) then
        nextExpire = bar.expirationTime;
      elseif (bar.expirationTime < nextExpire) then
        nextExpire = bar.expirationTime;
      end
    end

    if (nextExpire) then
      recheckTimer = timer:ScheduleTimer(recheckTimers, nextExpire - now);
    end
  end

  local function bigWigsEventCallback(event, ...)
    if (event == "BigWigs_Message") then
      WeakAuras.ScanEvents("BigWigs_Message", ...);
    elseif (event == "BigWigs_StartBar") then
      local addon, spellId, text, duration, icon = ...
      local now = GetTime();
      local expirationTime = now + duration;

      local newBar;
      bars[text] = bars[text] or {};
      local bar = bars[text];
      bar.addon = addon;
      bar.spellId = spellId;
      bar.text = text;
      bar.duration = duration;
      bar.expirationTime = expirationTime;
      bar.icon = icon;
      WeakAuras.ScanEvents("BigWigs_StartBar", spellId);
      if (nextExpire == nil) then
        recheckTimer = timer:ScheduleTimer(recheckTimers, expirationTime - now);
        nextExpire = expirationTime;
      elseif (expirationTime < nextExpire) then
        timer:CancelTimer(recheckTimer);
        recheckTimer = timer:ScheduleTimer(recheckTimers, expirationTime - now);
        nextExpire = expirationTime;
      end
    elseif (event == "BigWigs_StopBar") then
      local addon, text = ...
      if(bars[text]) then
        WeakAuras.ScanEvents("BigWigs_StopBar", text);
        bars[text] = nil;
      end
    elseif (event == "BigWigs_StopBars"
            or event == "BigWigs_OnBossDisable"
            or event == "BigWigs_OnPluginDisable") then
      local addon = ...
      for key, bar in pairs(bars) do
        if (bar.addon == addon) then
          bars[key] = nil;
          WeakAuras.ScanEvents("BigWigs_StopBar", key);
        end
      end
    end
  end

  function WeakAuras.RegisterBigWigsCallback(event)
    if (registeredBigWigsEvents [event]) then
      return
    end
    if (BigWigsLoader) then
      BigWigsLoader:RegisterMessage(event, bigWigsEventCallback);
      registeredBigWigsEvents [event] = true;
    end
  end

  function WeakAuras.RegisterBigWigsTimer()
    WeakAuras.RegisterBigWigsCallback("BigWigs_StartBar");
    WeakAuras.RegisterBigWigsCallback("BigWigs_StopBar");
    WeakAuras.RegisterBigWigsCallback("BigWigs_StopBars");
    WeakAuras.RegisterBigWigsCallback("BigWigs_OnBossDisable");
  end

  function WeakAuras.CopyBigWigsTimerToState(bar, states, id)
    states[id] = states[id] or {};
    local state = states[id];
    state.show = true;
    state.changed = true;
    state.addon = bar.addon;
    state.spellId = bar.spellId;
    state.text = bar.text;
    state.name = bar.text;
    state.duration = bar.duration;
    state.expirationTime = bar.expirationTime;
    state.resort = true;
    state.progressType = "timed";
    state.icon = bar.icon;
  end

  function WeakAuras.BigWigsTimerMatches(id, addon, spellId, textOperator, text)
    if(not bars[id]) then
      return false;
    end

    local v = bars[id];
    local bestMatch;
    if (addon and addon ~= v.addon) then
      return false;
    end
    if (spellId and spellId ~= v.spellId) then
      return false;
    end
    if (text) then
      if(textOperator == "==") then
        if (v.text ~= text) then
          return false;
        end
      elseif (textOperator == "find('%s')") then
        if (v.text == nil or not v.text:find(text)) then
          return false;
        end
      elseif (textOperator == "match('%s')") then
        if (v.text == nil or v.text:match(text)) then
          return false;
        end
      end
    end
    return true;
  end

  function WeakAuras.GetAllBigWigsTimers()
    return bars;
  end

  function WeakAuras.GetBigWigsTimerById(id)
    return bars[id];
  end

  function WeakAuras.GetBigWigsTimer(addon, spellId, text, operator)
    local bestMatch
    for id, bar in pairs(bars) do
      if (WeakAuras.BigWigsTimerMatches(id, addon, spellId, text, operator)) then
        if (bestMatch == nil or bar.expirationTime < bestMatch.expirationTime) then
          bestMatch = bar;
        end
      end
    end
    return bestMatch;
  end

  local scheduled_scans = {};

  local function doBigWigsScan(fireTime)
    WeakAuras.debug("Performing BigWigs scan at "..fireTime.." ("..GetTime()..")");
    scheduled_scans[fireTime] = nil;
    WeakAuras.ScanEvents("BigWigs_Timer_Update");
  end
  function WeakAuras.ScheduleBigWigsCheck(fireTime)
    if not(scheduled_scans[fireTime]) then
      scheduled_scans[fireTime] = timer:ScheduleTimer(doBigWigsScan, fireTime - GetTime() + 0.1, fireTime);
      WeakAuras.debug("Scheduled BigWigs scan at "..fireTime);
    end
  end

end
```

**Comment by funkydude** [comment] 2016-09-21 13:42
When searching your WTF folder, you should have got multiple hits from the BigWigs saved variables, unless you're ignoring them for the sake of this issue.

Same goes for searching the Interface folder, was WeakAuras the only addon with hits?

**Comment by Malcanthet** [comment] 2016-09-21 14:03
I was ignoring them (the bigwigs/littlewigs luas) on purpose since I assumed the hits would be plenty there but that's to be expected and I assumed unrelated to the issue if I copuld of course have assumed wrong, My knowledge on these issues is limited at best. Not had time to search through every single file yet. The ones I know will have them is the bigwigs.lua in addonskins. Is there anything I can exclude from the search to perhaps speed up the process? Again I'm ignoring bigwigs/littlewigs luas, mostly because I know the hits will be there and I'm unsure how to limit it to what will be useful.

**Comment by funkydude** [comment] 2016-09-21 14:07
Don't search every file manually. Open notepad++, press ctrl+f, navigate to "Find in Files", type in BigWigs, set the directory to your WoW directory and hit "Find All".

**Comment by Malcanthet** [comment] 2016-09-21 15:23
Now I feel silly. Especially since I've used that function before.

WTF:

```
BigWigs3DB = {
		["BigWigs_Plugins_Victory"] = {
		["BigWigs_Plugins_Alt Power"] = {
		["BigWigs_Plugins_Sounds"] = {
		["BigWigs_Bosses_Ivanyr"] = {
		["BigWigs_Plugins_Statistics"] = {
		["BigWigs_Plugins_BossBlock"] = {
		["BigWigs_Bosses_Naltira"] = {
		["BigWigs_Plugins_Colors"] = {
		["BigWigs_Plugins_Raid Icons"] = {
		["BigWigs_Bosses_Corstilax"] = {
		["BigWigs_Plugins_Bars"] = {
					["BigWigsAnchor_width"] = 199.999877929688,
					["BigWigsEmphasizeAnchor_width"] = 299.999938964844,
					["BigWigsAnchor_y"] = 140,
					["BigWigsAnchor_x"] = 17,
					["BigWigsEmphasizeAnchor_width"] = 154.166732788086,
					["BigWigsEmphasizeAnchor_x"] = 416,
					["BigWigsEmphasizeAnchor_y"] = 350,
					["BigWigsAnchor_width"] = 384.166442871094,
					["BigWigsAnchor_width"] = 199.999877929688,
					["BigWigsEmphasizeAnchor_width"] = 299.999938964844,
					["BigWigsAnchor_y"] = 140,
					["BigWigsAnchor_x"] = 17,
					["BigWigsEmphasizeAnchor_width"] = 154.166732788086,
					["BigWigsEmphasizeAnchor_x"] = 640,
					["BigWigsEmphasizeAnchor_y"] = 230,
					["BigWigsAnchor_width"] = 384.166320800781,
		["BigWigs_Plugins_Messages"] = {
		["BigWigs_Plugins_Super Emphasize"] = {
		["BigWigs_Bosses_Advisor Vandros"] = {
		["BigWigs_Plugins_Proximity"] = {
		["BigWigs_Plugins_Respawn"] = {
		["BigWigs_Bosses_General Xakal"] = {
		["BigWigs_Plugins_Pull"] = {
BigWigs3IconDB = {
BigWigsStatisticsDB = {
BigWigs3DB = {
		["BigWigs_Plugins_Victory"] = {
		["BigWigs_Plugins_Colors"] = {
		["BigWigs_Plugins_Alt Power"] = {
		["BigWigs_Plugins_BossBlock"] = {
		["BigWigs_Plugins_Bars"] = {
					["BigWigsEmphasizeAnchor_width"] = 299.999938964844,
					["BigWigsAnchor_width"] = 199.999877929688,
					["BigWigsAnchor_y"] = 140,
					["BigWigsEmphasizeAnchor_y"] = 350,
					["BigWigsAnchor_x"] = 20,
					["BigWigsEmphasizeAnchor_width"] = 149.166625976563,
					["BigWigsEmphasizeAnchor_x"] = 419,
					["BigWigsAnchor_width"] = 380.833160400391,
					["BigWigsAnchor_y"] = 140,
					["BigWigsAnchor_x"] = 20,
					["BigWigsEmphasizeAnchor_y"] = 225,
					["BigWigsEmphasizeAnchor_width"] = 149.166625976563,
					["BigWigsEmphasizeAnchor_x"] = 645,
					["BigWigsAnchor_width"] = 380.833160400391,
		["BigWigs_Plugins_Super Emphasize"] = {
		["BigWigs_Plugins_Sounds"] = {
		["BigWigs_Plugins_Respawn"] = {
		["BigWigs_Plugins_Statistics"] = {
		["BigWigs_Plugins_Messages"] = {
		["BigWigs_Plugins_Proximity"] = {
		["BigWigs_Plugins_Raid Icons"] = {
BigWigs3IconDB = {
BigWigsStatisticsDB = {
				["BigWigs"] = false,
				["BigWigs"] = false,
BigWigs_Cataclysm: disabled
BigWigs_Cataclysm: disabled
```
[AddOns.txt](https://github.com/BigWigsMods/BigWigs/files/485392/AddOns.txt)

**Comment by funkydude** [comment] 2016-09-21 15:42
Nothing really points out to me unfortunately. The only thing I can think of is a buggy WeakAura. I would say try and see if you can reproduce it with WA disabled, but you said it's already difficult to reproduce.

The other option is exit the game, completely delete your SavedVariables files and start fresh.

**Comment by Malcanthet** [comment] 2016-09-21 16:21
I deleted all the saved variables bar the elvui and weakauras ones a couple of days ago. I'll see about disabling weak auras, I'd hate to have to rewrite all of them (all classes, mutliple specs) but if I have to I have to same goes for elvui, will have to do those when I get some spare time and do one at a time. If I ever localise it. I'll be sure to let you know. Thanks for all the help!

**Comment by funkydude** [comment] 2016-09-21 16:29
>I deleted and re-did all the saved variables bar the elvui and weakauras ones a couple of days ago.

Yet it's happened since you did that I assume? :/

>I'd hate to have to rewrite all of them

There would be no reason for this, the ones you've wrote yourself you know aren't making changes. My assumption here is a foreign string, I'm probably wrong.

**Comment by Malcanthet** [comment] 2016-09-21 16:41
Yeah, sadly it did. I'll recheck them, I'm assuming the auras have to be loaded for it to actually cause an error? If that's the case it eliminates all but the shaman ones, I'll have a look through them tonight/tomorrow and see if I can find something.

**Comment by Malcanthet** [comment] 2016-10-12 06:06
Just thought I'd check in again. I was planning on writing a couple of days ago since I'd had no issues then irony struck and gave the same issue on that day, I felt a strong urge to bang my head against my keyboard. Apart from that one issue (heroic Neltharion's lair) I've not had any problems though. I'd removed the two things that I thoguht may have been the culprits (some weird WA remenant from using Iskar Assist back in WoD (deleted) and a custom cloudburst totem WA (also deleted)) alas it turns out I was mistaken. At this point I have no idea what causes it still and since it's so rare it's hard to test since I can't seem to force it to appear.

Question: Could WA's that don't use custom code still cause issues?

**Comment by funkydude** [comment] 2016-10-12 12:55
Not to my knowledge, no. At this point if it takes 21 days to try and reproduce it there's really nothing more we can do. Going to close this, feel free to add to it if you resolve it.

**Comment by Malcanthet** [comment] 2016-10-27 10:15
I think I've worked out what actually causes it to reset, no idea why it does it though. I have dual spec settings enabled (dps and heal) and they're set to auto switch when I spec switch, when I do that it wipes the regular bar scale and the text/time align. I kept switching btwn the two in EN last night and it kept wiping the settings. A relog fixes it.

**Comment by Malcanthet** [comment] 2016-10-27 10:17
Leaving actual error:

`3x BigWigs_Plugins\Bars.lua:882: attempt to compare two nil values
BigWigs_Plugins\Bars.lua:882: in function <BigWigs_Plugins\Bars.lua:881>
[C]: in function `sort'
BigWigs_Plugins\Bars.lua:900: in function <BigWigs_Plugins\Bars.lua:885>
BigWigs_Plugins\Bars.lua:936: in function <BigWigs_Plugins\Bars.lua:931>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...BL_Cooldown\libs\LibCandyBar-3.0\LibCandyBar-3.0-93.lua:326: in function `Stop'
BigWigs_Plugins\Bars.lua:1286: in function `?'
BigWigs\Loader.lua:652: in function `SendMessage'
BigWigs_Core\BossPrototype.lua:242: in function <BigWigs_Core\BossPrototype.lua:199>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0-12.lua:593: in function <ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:586>
(tail call): ?
BigWigs_Core\BossPrototype.lua:738: in function `Win'
BigWigs_Core\BossPrototype.lua:828: in function `?'
BigWigs_Core\Core.lua:50: in function <BigWigs_Core\Core.lua:45>

Locals:
nil`

**Comment by funkydude** [comment] 2016-12-10 23:54
>when I do that it wipes the regular bar scale and the text/time align

Only these 3 settings? Nothing else?

I've tried to reproduce it by creating 3 spec profiles but nothing is reset when I switch. This was using a clean WTF profile, but I assume you tried this?

**Comment by Malcanthet** [comment] 2016-12-11 09:44
I did yes, I'll try it again tonight and re-check what changes since I've had it on manual switch for some time now.

**Comment by funkydude** [comment] 2016-12-12 00:03
It could be an issue with the spec swapping library, but it would be an odd one if it was only those 3 options.

**Comment by Malcanthet** [comment] 2016-12-12 07:50
I retested it last night. Even if I have the spec switch enabled or not (as in it changes for me or I manually change it) doesn't seem to matter. I still get an error, however, unlike before I now do still get all the bars showing I couldn't see any settings actually restetting in the options this time. The error I get is this:

Message: Interface\AddOns\BigWigs\Loader.lua:653: attempt to call field '?' (a nil value)
Time: 12/11/16 21:14:49
Count: 244
Stack: [C]: in function `?'
Interface\AddOns\BigWigs\Loader.lua:653: in function `SendMessage'
Interface\AddOns\BigWigs\Loader.lua:816: in function `?'
Interface\AddOns\BigWigs\Loader.lua:682: in function <Interface\AddOns\BigWigs\Loader.lua:681>

**Comment by funkydude** [comment] 2016-12-12 11:01
That error doesn't seem related at all. I doubt you'd get that error with only BigWigs enabled.

**Comment by Malcanthet** [comment] 2016-12-12 11:14
It only started appearing a couple of weeks ago as well so most likely (as you say) another issue altogether, the original issue I had doesn't seem to be happening any more though (since that would just make the bars stop appearing altogether) which is a good thing. I'll work on seeing if I can find what add-ons causing this issue.

**Comment by funkydude** [comment] 2016-12-13 15:02
That error should now be prevented by the callback restrictions in the latest release.

**Comment by Malcanthet** [comment] 2016-12-17 08:44
Tried it and still getting this:

Message: Interface\AddOns\BigWigs_Plugins\Bars.lua:1456: Usage: <unnamed>:SetJustifyH("justify")
Time: 12/17/16 09:28:58
Count: 1
Stack: [C]: ?
[C]: in function `SetJustifyH'
Interface\AddOns\BigWigs_Plugins\Bars.lua:1456: in function `?'
Interface\AddOns\BigWigs\Loader.lua:633: in function `SendMessage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:1484: in function `CDBar'
...s\LittleWigs\Legion\HallsOfValor\God-KingSkovald.lua:36: in function `OnEngage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:726: in function `Engage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:549: in function `?'
Interface\AddOns\BigWigs_Core\Core.lua:45: in function <Interface\AddOns\BigWigs_Core\Core.lua:40>

Locals: 

When I spec swapped outside of dungeon after I left it came up with this:

Message: Interface\AddOns\BigWigs\Loader.lua:609: :RegisterMessage(message, function) attempted to register the function 'OnDBMSync' but it doesn't exist!
Time: 12/17/16 09:36:35
Count: 1
Stack: (tail call): ?
[C]: in function `error'
Interface\AddOns\BigWigs\Loader.lua:609: in function `RegisterMessage'
Interface\AddOns\BigWigs_Plugins\Bars.lua:1075: in function `v'
Interface\AddOns\BigWigs\Loader.lua:631: in function `SendMessage'
Interface\AddOns\BigWigs_Core\Core.lua:294: in function <Interface\AddOns\BigWigs_Core\Core.lua:293>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...rface\AddOns\ElvUI\Libraries\AceDB-3.0\AceDB-3.0.lua:465: in function `SetProfile'
...igWigs_Core\Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua:184: in function `CheckDualSpecState'
...igWigs_Core\Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua:416: in function <...igWigs_Core\Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua:400>

Locals: <none>

Here are screenshots of bar settings after error (seems I was wrong earlier it wipes most things it seems).

[](http://imgur.com/igTpupT)
[](http://imgur.com/DkqBjEl)
[](http://imgur.com/Nd51Y6W)
[](http://imgur.com/tcnTAVe)

**Comment by funkydude** [comment] 2016-12-17 13:37
Fixed that second error.

**Comment by funkydude** [comment] 2017-01-11 02:43
First error is probably fixed by https://github.com/BigWigsMods/BigWigs/commit/ea16aa5479f9f7b3774b8fa9d4b7e51c2b46f09e

**Closed by funkydude** 2017-01-11 02:43 UTC
