### ISSUE TITLE
No way to disable forced Nameplates feature

### ISSUE THREAD

**Issue by bloodgrom** [BigWigsMods/BigWigs#1879] opened 2024-10-12 17:08 UTC
## Describe the problem
Adding nameplate icons and text to all nameplates without a way to turn them all off at once and cluttering the screeen with undesired information. The only way to turn them off is to manually turn each ability off in the advaced option for each ability which is absurd. Features such as this that massively alter gameplay should be opt-in by default and at worst you should be able to easily turning them off, not requiring to manually disable hundreds of abilities.

### What steps will reproduce the problem?

1.  Install LittleWigs
2.  Enter Dungeon
3.  Fight trash mobs

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 366 (eaf08ce)

**Comment by funkydude** [comment] 2024-10-12 17:19
Consider opting in to using the search feature.
Duplicate of #1784

**Closed** 2024-10-12 17:19 UTC
Labels: retail
