### ISSUE TITLE
Can't set font size to 8 for Bars due to new minimum sizes.

### ISSUE THREAD

**Issue by p1xelHer0** [BigWigsMods/BigWigs#1875] opened 2024-10-08 21:22 UTC
## Describe the problem

I use a "pixel perfect" font called PF Tempesta Seven which looks very crisp at font size 8. With the recent commit https://github.com/BigWigsMods/BigWigs/commit/9fcc1baa265d286ebd159562db3e0421605f0081 I now can't set the font size to 8, only 10, which results in my UI looking like this: 
![bild](https://github.com/user-attachments/assets/8e43d00f-9ba2-4743-99b9-f364158fbc39)
Whereas it should look like this (example from my ElvUI frame): 
![bild](https://github.com/user-attachments/assets/c95a1929-1d14-4df6-9010-c75e40ce5bd8)

### What steps will reproduce the problem?

1. Try to use BigWigs Bars with a font with size 8.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

See above.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v365.3.zip in the CurseForge Client

### Do you have an error log of what happened?

N/A

### Any additional information? (example: WoW language if not English)

I would _really_ appreciate if we could select smaller font sizes (But where do we set the limit, I don't know. ElvUI has a lower limit of 8 if that matters). 

This way I would not have to maintain a local modified version of BigWigs which I would really appreciate! Thank you <3

**Comment by funkydude** [comment] 2024-10-09 03:51
This looks like an exact duplicate of #1871
You can try some of the suggested fonts there

**Closed** 2024-10-10 22:45 UTC
Labels: retail
