### ISSUE TITLE
Mythic Guarm marks.

### ISSUE THREAD

**Issue by dreamslaveone** [BigWigsMods/BigWigs#116] opened 2016-11-28 10:25 UTC
### What steps will reproduce the problem?  
1. Enable option to mark players on foam debuff targets (star, circle, diamond).
2.  After some time or after wipe marks doesnt reset and BigWigs places additional marks like skill, moon, etc
3.  

### What version of BigWigs are you using?
v25.1-3-g0ef8230

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
ruRU client

P.S. Is there possibility to place marks only on people with two different color debuffs? I'll explain a bit: healers need to dispel people who has two debuffs with different colors, like red breath and blue foam. There is no need to mark player with both red debuffs.

**Comment by elvador** [comment] 2016-12-01 14:01
I'm not able to reproduce this. 
Are you sure BigWigs is setting the wrong marks?


> P.S. Is there possibility to place marks only on people with two different color debuffs? I'll explain a bit: healers need to dispel people who has two debuffs with different colors, like red breath and blue foam. There is no need to mark player with both red debuffs.

This check is not needed because Guarm doesn't place the same colored dispel debuff on players with the given breath debuff. It's possible that players do not need a dispel on the first debuffs, because they are applied before the first breath, but thats nothing BigWigs can handle.

**Comment by ManagerWoW** [comment] 2016-12-01 14:42
Seeing this as well. Doesn't happen every reset though.

As for the marking logic, Guarm can Foam people with the same color debuff. It would be nice if those people weren't marked.

**Comment by funkydude** [comment] 2016-12-01 14:59
>Seeing this as well. Doesn't happen every reset though. Once it does bug, it stays bugged until reloading.

What exactly is staying bugged until reloading? Please name the specific functionality.
The table that contains the player names is erased in 3 different locations, so there's no chance that it could be bringing forth players from a previous attempt to mark, which leads me to wonder what you are seeing as being bugged, because that's the only thing that would be resolved by a reload.

**Comment by ManagerWoW** [comment] 2016-12-01 16:48
The target markers on the Foam targets. Usually it is 1-3 (star / circle / diamond), but sometimes after wipes/resetting the boss, it will be 4-6 (triangle / moon / square).

A UI reload is required to reset the foam incrementer to 1 again.

**Comment by funkydude** [comment] 2016-12-01 16:58
That is not possible I'm afraid. For that to happen means the table never got erased, which it is after a wipe and on pull. Did you reload straight after 1 wipe or did it persist across 2+ wipes?

Can you confirm (via chat messages) that you are infact the one setting the marks, and that you don't have other addons setting marks, such as DBM or WeakAuras?

**Comment by elvador** [comment] 2016-12-01 17:16
> As for the marking logic, Guarm can Foam people with the same color debuff. It would be nice if those people weren't marked.

@ManagerWoW Can you send me a log of the initial debuff being applied to a target which has the same colored breath debuff?

**Comment by ManagerWoW** [comment] 2016-12-01 18:23
@elvador I take that back, I was wrong on the same color debuffs.

@funkdude I'll do some more testing on it tonight.

**Comment by Winney1907** [comment] 2016-12-05 23:00
I can confirm that after 20 or so wipes without a UI reload Big Wigs begins to assign incorrect markers and subsequently non-existing markers.

**Comment by funkydude** [comment] 2016-12-06 10:14
@Winney1907 Thanks but that is not useful information.

**Comment by ManagerWoW** [comment] 2016-12-09 03:31
http://manager.heroicstrike.org/WoWScrnShot_120816_201554.jpg

Whenever it bugs, the first set will always mark correctly. The 2nd set and onwards will be using marks 4-6. It will stay bugged until a UI reload is done.

It looks like it is never clearing the first set of marks 1/2/3, so they are already in use for the 2nd round of marks.

**Closed** 2016-12-09 04:14 UTC
