### ISSUE TITLE
[Feature Request] Count Abilities

### ISSUE THREAD

**Issue by gehteuch** [BigWigsMods/BigWigs#361] opened 2017-08-18 13:12 UTC
Hi,

I know you usually add ability counters for abilites you think are important but sometimes it would be nice to have a counter on spells not everyone has to track like Bufferfish on Mistress. It would be great to just have a checkbox on the bar options for Bosstimers that would add a counter to the bar.

**Comment by elvador** [comment] 2017-08-18 13:19
Duplicate of #139.

**Closed by elvador** 2017-08-18 13:19 UTC
