### ISSUE TITLE
Option for disabling nameplate CD's missing

### ISSUE THREAD

**Issue by Sebastian1989101** [BigWigsMods/BigWigs#1800] opened 2024-09-08 16:41 UTC
As title said, a option to disabled BigWigs new nameplate CD's is missing. This is annoying as it interferes with my UI a lot and I already have a way better WeakAura for this feature.

**Comment by funkydude** [comment] 2024-09-08 16:45
Duplicate of #1784

Also the WA is not "way better" unless you enjoy a lower average FPS. If you find a feature lacking then feel free to submit suggestions.

**Closed by funkydude** 2024-09-08 16:45 UTC
Labels: retail
