### ISSUE TITLE
Cenarius -Multiple Rotten breath countdowns when more then one drake are up

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#96] opened 2016-11-14 01:01 UTC
You get two countdowns when two drakes are up, even with "Show multiple rotten breath bars" unchecked

**Comment by elvador** [comment] 2016-11-14 01:03
The two countdowns you hear are the cooldown of the ability and the cast itself. This is the standard behavior and not a bug.

**Comment by cexikitin** [comment] 2016-11-14 01:23
Im hearing three countdowns in a row

First drake cooldown
Second drake cooldown
First Drake casting

**Comment by elvador** [comment] 2016-11-14 01:31
Fixed now, thanks

**Closed** 2016-11-14 01:31 UTC
