### ISSUE TITLE
[Feature Request] Only emphasize the bars I want

### ISSUE THREAD

**Issue by MSav93** [BigWigsMods/BigWigs#887] opened 2020-12-20 10:15 UTC
## Describe the problem
I'd like to use Emphasized bars to make spells obvious, however when they're enabled they automatically enable for all boss timers via the "Emphasize at... (seconds)" option. I'd like to be able to have BigWigs Emphasize ONLY user chosen bars and not based on time remaining.

It kind of defeats the purpose (for me at least) if all abilities are moved up to the emphasized section i.e. if everything is emphasized then nothing is.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
9.0.11

### Any additional information? (example: WoW language if not English)
I hope there isn't an obvious option that I've missed to do this.

**Comment by funkydude** [comment] 2020-12-20 16:00
Thanks for the request.
Duplicate of #476

**Closed by funkydude** 2020-12-20 16:00 UTC
Labels: retail
