### ISSUE TITLE
Emphasized Bar color issue

### ISSUE THREAD

**Issue by Surarn** [BigWigsMods/BigWigs#1680] opened 2024-06-26 15:04 UTC
## Describe the problem
Changing the color of the Emphasized bar under Colors -> Bars -> Emphasized from the default Red to something else prohibits changing the color of the Emphasized bar for specific abilities to the exact same Red color. RGB 255,0,0 doesnt work however 254,0,0 works.

### What steps will reproduce the problem?

1.  Change the color of the Emphasized bar under Options -> Colors -> Emphasized away from the default Red.
2.  Go to either Raid Bosses or Dungeon Bosses, press the Arrow to access any ability, go to Colors and change the Emphasized color to exactly RGB 255,0,0, change tab to either Advanced Options or Sounds or press "Back" and go back into the same ability.
3.  The color is now back to your "Global" emphasized color selected in Step 1 and not the Red color selected in Step 2.

Only tried with Emphasized bars.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Alpha release of BigWigs 338 (e118652)

**Comment by ntowle** [comment] 2024-06-26 15:12
Duplicate of https://github.com/BigWigsMods/BigWigs/issues/1346 (try 254 instead of 255)

**Closed by ntowle** 2024-06-26 15:12 UTC
Labels: retail
