### ISSUE TITLE
[Feature Request] Rename abilities

### ISSUE THREAD

**Issue by coup321** [BigWigsMods/BigWigs#1517] opened 2023-12-19 22:15 UTC
## Describe the problem
I want to be able to rename abilities that go on status bars.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
I would like it to look like this:
![image](https://github.com/BigWigsMods/LittleWigs/assets/7375214/1b863653-57d7-4e09-868a-91ff0dbdc749)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
Latest

### Any additional information? (example: WoW language if not English)
I build in the functionality that I want by creating a new lua file building a global table _G.bigwigs_name_overrides and then adding the following lines to BossPrototype.lua starting at line 2643 in the current (12/19/2023) version of the file.
```
        local msg = textType == "string" and text or spells[text or key]
        if _G.big_wigs_overrides[msg] then
            msg = _G.big_wigs_overrides[msg]
        end
```

The custom table looks like this (limited section of the table):

```
_G.big_wigs_overrides = {
    ...
    ['Chrono-faded'] = 'Debuffs',
    ['Fragments of Time'] = 'Orbs',
    ['Corrosive Infusion'] = 'Debuff',
    ['Blight Reclamation'] = 'Breath (Clears)',
    ['Necrotic Winds'] = 'Winds',
    ...
}
```

I'm happy to contribute to the project if this is a feature that would be in line with the addon's goals.
C

**Comment by ntowle** [comment] 2023-12-19 22:27
Duplicate of #655

**Closed by ntowle** 2023-12-19 22:27 UTC
Labels: retail
