### ISSUE TITLE
Voice and Nameplates General off option

### ISSUE THREAD

**Issue by G1ak1** [BigWigsMods/BigWigs#1779] opened 2024-08-28 22:08 UTC
Hello.

I would like to ask for a general OFF button to be added for Voice and nameplates so we can turn them off for all abilities at once and then go to each boss/trash and turn on only the ones we want. its really spammy to have them on for everything and would take hours to go one by one on every ability to turn them off.

can this be done?

thank u

**Comment by funkydude** [comment] 2024-08-28 22:42
Duplicate of #1760

**Closed by funkydude** 2024-08-28 22:42 UTC
Labels: retail
