### ISSUE TITLE
What is BW licensed under?

### ISSUE THREAD

**Issue by Avyiel** [BigWigsMods/BigWigs#813] opened 2020-06-26 18:52 UTC
Title. I wish to know what license is BW under, since there is no `LICENSE` file in the root folder.

**Comment by nebularg** [comment] 2020-06-26 18:54
All Rights Reserved: You are free to fork and modify on GitHub, please ask us about anything else.

**Comment by Avyiel** [comment] 2020-06-26 19:09
Right. I will then maintain a personal fork of BW, which is allowed per the license.

I also wish to redistribute this fork, as a modification of the Addon. Under what terms can I do that?

**Comment by nebularg** [comment] 2020-06-26 19:28
You may not redistribute it. But the plugin system is pretty flexible, so feel free to add and release whatever you'd like with that.

**Comment by Avyiel** [comment] 2020-06-26 19:47
Right. I'll be explicit about what plugins I will release then, so that there is not copyright confusion down the line:

1. Dungeon modules. Since LittleWigs has no boss modules for any Classic dungeons I will write and release my own.
2. Dungeon statistics. While there is a statistics plugin, it only handles raids. I also want dungeons to be tracked.

**Comment by nebularg** [comment] 2020-06-26 19:54
I'm not sure what the point of releasing your own LittleWigs is. Dungeon stats can also be tracked without adding a bunch of pointless modules.

**Comment by Avyiel** [comment] 2020-06-26 20:05
I submitted a PR to track dungeon stats already. You closed it based on "feature not wanted". That's why I'll keep a fork of the core addon, honestly. 

The point of releasing my own modules is that I then control what goes in there and therefore will be able to add modifications that otherwise wouldn't be approved into the upstream repo (read: AI bars and stats).

**Comment by elvador** [comment] 2020-06-26 21:15
You straight up copied code from DBM and wanted to include it in BigWigs. Of course that's not going to get merged. 

And as neb already mentioned, you can just extend existing functionality via plugins (i.e. adding dungeon stats), no need for a full fork.

**Comment by Avyiel** [comment] 2020-06-26 21:38
> You straight up copied code from DBM and wanted to include it in BigWigs. Of course that's not going to get merged.

Licensing fully allows me to use DBM code wherever I wish to do so. Their code is under CC 3.0
Code taken from their repo won't make it's way in here for other reasons, and that is that's your choice as maintainers of the project. I accepted that, and I don't intend to discuss that PR or that point at all. 

> And as neb already mentioned, you can just extend existing functionality via plugins (i.e. adding dungeon stats), no need for a full fork.

The simplest way to track dungeon stats is by leveraging the already-existing `Statistics` plugin. It works perfectly. You can check #809 for the solution I came up with. I don't believe implementing a separate plugin for dungeon stats will integrate as nicely.

Regardless, I opened up this issue to ask about licensing and re-distribution. As it turns out, I cannot redistribute. That's fine. What I can do is fork and keep a copy with the functionality I desire, so that's what I'll do. 

What I will not do anymore is try to submit feature PRs. I'd still like to contribute with bug fixes though, but I'll open up issues first and only submit PRs if there is interest from your part, as I now believe that PRs without the previous approval of the maintainers are a waste of time.

**Closed** 2020-06-28 06:24 UTC

**Comment by Thaodan** [comment] 2025-02-19 20:20
I noticed this kind of licensing in other addons. While this issue is quite old I want to add my points

> > You straight up copied code from DBM and wanted to include it in BigWigs. Of course that's not going to get merged.
> 
> Licensing fully allows me to use DBM code wherever I wish to do so. Their code is under CC 3.0 Code taken from their repo won't make it's way in here for other reasons, and that is that's your choice as maintainers of the project. I accepted that, and I don't intend to discuss that PR or that point at all.

The issue is that would change mean that BigWigs would have to abide by the Law and the composition of the addon i.e. the installed addon would be under the strongest license.

**Comment by Thaodan** [comment] 2025-02-19 20:25
> You may not redistribute it. But the plugin system is pretty flexible, so feel free to add and release whatever you'd like with that.

Doesn't forking already count as distribution? Also you can't fully enforce copyright if you don't own the copyright of all the contributors.
