### ISSUE TITLE
Lua error...

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs#1354] opened 2023-02-20 22:25 UTC
## Describe the problem
Had a lag spike and lua error today in LFR during the encounter

### What steps will reproduce the problem?

1.  none 
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

BigWigs-v266.2.zip

### Do you have an error log of what happened?

2x BigWigs/Loader.lua:1081: script ran too long
[string "@BigWigs/Loader.lua"]:1081: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2874: in function `PlaySound'
[string "@LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua"]:331: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:564: in function <BigWigs_Core/BossPrototype.lua:530>

Locals:
self = <table> {
 DeadlyWinds = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:335
 DetonationSeeds = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:369
 MonotonousLecture = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:317
 colorOptions = <table> {
 }
 enableMobs = <table> {
 }
 ExpelIntruders = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:329
 ArcaneRainSuccess = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:291
 ArcaneRain = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:286
 CallOfTheFlock = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:355
 Riftbreath = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:298
 toggleDefaults = <table> {
 }
 optionHeaders = <table> {
 }
 name = "BigWigs_Bosses_Algeth'ar Academy Trash"
 DisruptingPulse = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:381
 localization = <table> {
 }
 sayCountdowns = <table> {
 }
 enabled = true
 AstralWhirlwindDamage = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:402
 soundOptions = <table> {
 }
 CelestialShieldApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:457
 instanceId = 2526
 StormSlash = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:341
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:1062
 OnBossEnable = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:117
 MysticBlast = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:281
 ManaVoid = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:269
 BronzePledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:237
 GuardianSentryDeath = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:347
 AstralBombRemoved = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:444
 db = <table> {
 }
 SendMessage = <function> defined @BigWigs/Loader.lua:1076
 GreenPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:251
 AstralBomb = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:418
 AstralWhirlwind = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:390
 toggleOptions = <table> {
 }
 BluePledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:244
 Gust = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:360
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 AstralBombApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:430
 RegisterMessage = <function> defined @BigWigs/Loader.lua:1041
 displayName = "Trash"
 RedPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:258
 ViciousAmbush = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:303
 CelestialShield = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:452
 BlackPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:230
 GOSSIP_SHOW = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:207
 moduleName = "Algeth'ar Academy Trash"
 UnregisterEvent = <function> defined @BigWigs_Core/Core.lua:71
 CHAT_MSG_MONSTER_SAY = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.l

**Comment by Milky063** [comment] 2023-02-20 22:25
forgot to add this one as well...

1x BigWigs is missing timers on "LFR" running 266-d3260c4, tell the devs!
New timer for "373405" at stage 1 with placement 1 and value 34.03.
[string "@BigWigs_Core/BossPrototype.lua"]:436: in function `?'
[string "@Chatter/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...ceChatter/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by funkydude** [comment] 2023-02-20 22:37
This is a duplicate of your original issue here: https://github.com/BigWigsMods/LittleWigs/issues/882
Closing this one

**Closed by funkydude** 2023-02-20 22:37 UTC
Labels: retail
