### ISSUE TITLE
Emphasized bars can not be recolored

### ISSUE THREAD

**Issue by ruuuudyyyy** [BigWigsMods/BigWigs#1467] opened 2023-11-26 17:28 UTC
## Describe the problem
Customizing the color of the Emphasized Bar does not work.
Normal Bar and Text do work.

### What steps will reproduce the problem?

1.  Go to Boss spell (example Gnarlroot - Dreadfire Barrage)
2.  Tab on Colors
3.  Try to change Color of Bars - Emphasized

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Attached .gif
![Wow_sBkCVmWp4y](https://github.com/BigWigsMods/BigWigs/assets/77745731/01e942b6-22da-45f8-b9e5-a2168e18ec21)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
301 (a5cb0a0)

### Do you have an error log of what happened?
no.

### Any additional information? (example: WoW language if not English)
Running wow on english. Using other Addons like Weakaura. Nothing should interfere with BW tho.

**Comment by funkydude** [comment] 2023-11-26 17:36
Duplicate of #1346 (try 254 instead of 255)

**Closed by funkydude** 2023-11-26 17:36 UTC
Labels: retail
