### ISSUE TITLE
[Feature Request] Editable spell name aliases

### ISSUE THREAD

**Issue by calummitchell** [BigWigsMods/BigWigs#1493] opened 2023-12-10 14:23 UTC
I have a hard time remembering what each boss spell does from its name so it's great when bigwigs provides a simple more intuitive alias. However, aliases aren't provided for every spell and some of the aliases could be more descriptive e.g. instead of Blades for Igira - Twisted Blades I'd make it Frontal.

Some boss spells already have aliases e.g. Amirdrassil - Gnarlroot - Tortured Scream has the alias Scream. I'd like the ability for these aliases to be editable and for all spells to have an editable alias. Aliases would default to blank (unset) when bigwigs authors don't provide one. These aliases would be used for text to speech when the Voice option is checked.

I currently use the Raid Ability Timeline weakaura (https://wago.io/RaidAbilityTimeline) which allows me to provide aliases for all boss spells. I find this very helpful but the setup and long term management of it's custom options is a pain.

**Comment by funkydude** [comment] 2023-12-11 00:54
Duplicate of #655

**Closed by funkydude** 2023-12-11 00:54 UTC
Labels: retail
