### ISSUE TITLE
BigWigs causing freeze when entering dungeon instance

### ISSUE THREAD

**Issue by nohde** [BigWigsMods/BigWigs#774] opened 2020-02-27 15:21 UTC
### What steps will reproduce the problem?  
1.  BigWigs activated
2.  Enter dungeon instances

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v183.2

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Every time when entering a dungeon instance, whether by locator or premade group, the game freezes for approximately 20 seconds and this has only occurred when BigWigs is activated.
I've tried to disable all ADDONS (using only BigWigs and the standard Blizzard interface) and the same problem happens.
As I didn't find anything related to this, I believe it is an isolated problem. Any ideas of what may be causing this problem and how to solve it?

**Comment by Justw8** [comment] 2020-02-27 15:28
You also have Littlewigs active?

**Comment by nohde** [comment] 2020-02-27 15:34
Yes, but even without it the freeze happens.

**Comment by Citizen-alpha** [comment] 2020-03-06 13:07
I am having a similar issue. 

3x BigWigs\Loader.lua:322: script ran too long
[string "@BigWigs\Loader.lua"]:322: in function <BigWigs\Loader.lua:308>
[string "@BigWigs\Loader.lua"]:333: in function <BigWigs\Loader.lua:328>
[string "@BigWigs\Loader.lua"]:345: in function <BigWigs\Loader.lua:343>
[string "@BigWigs\Loader.lua"]:1291: in function `?'
[string "@BigWigs\Loader.lua"]:1027: in function <BigWigs\Loader.lua:1026>

**Comment by milotic** [comment] 2020-07-30 06:11
same here 

Date: 2020-07-30 00:10:11
ID: 15
Error occured in: Global
Count: 1
Message: ..\AddOns\BigWigs\Loader.lua line 322:
   script ran too long
Debug:
   [string "@BigWigs\Loader.lua"]:322:
      BigWigs\Loader.lua:308
   [string "@BigWigs\Loader.lua"]:333:
      BigWigs\Loader.lua:328
   [string "@BigWigs\Loader.lua"]:345:
      BigWigs\Loader.lua:343
   [string "@BigWigs\Loader.lua"]:1291: ?()
   [string "@BigWigs\Loader.lua"]:1027:
      BigWigs\Loader.lua:1026
Locals:
obj = nil
index = 217
loaded = true
reason = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LittleWigs"
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "ADDON_LOADED"
(*temporary) = "script ran too long"
loadOnSlash = <table> {
}
next = <function> defined =[C]:-1
sysprint = <function> defined @Interface\AddOns\BigWigs\Loader.lua:304

**Comment by elvador** [comment] 2020-07-30 10:59
@milotic Does it also happen with only BigWigs and LittleWigs (and BugSack and BugGrabber) enabled?

**Comment by milotic** [comment] 2020-07-30 20:21
@elvador yes and always happen in the first time of zoning a place example every day when i go to do vision the freeze happen only in the first vision the wow freeze like 20 -30 segs and bigwigs error popup, happen too when mouseover a world boss the first time

**Comment by elvador** [comment] 2020-07-31 08:29
Please do the following steps and let me know if it happens as well. This will delete your BigWigs settings. You can restore them by renaming the file to `BigWigs.lua` again. WoW must be closed to do so.

1. Close WoW
2. Navigate to `X:\World of Warcraft\_retail_\WTF\Account\YourAccountName\SavedVariables` (this path will vary depending on your WoW installation and your account name)
3. Find the `BigWigs.lua` file and rename it
4. Start WoW again, disable everything but the addons mentioned above and try again

**Comment by milotic** [comment] 2020-08-01 06:47
hi today i test this fix in 4 mythic dungeons and 1 vision and the error freeze is gone, tomorrow test with world boss and raids, but why deleting this fix our problem? in my case never touch bigwigs settings and only use the twitch app to autoupdate everyday

**Comment by elvador** [comment] 2020-08-01 12:01
Please share your renamed, old `BigWigs.lua` file, then we can have a look.

**Comment by milotic** [comment] 2020-08-01 20:11
[BigWigsold.log](https://github.com/BigWigsMods/BigWigs/files/5011177/BigWigsold.log)

only swap the .log to .lua i change to upload here

**Comment by milotic** [comment] 2020-08-02 05:58
hi im back today i try test again doing other vision and the issue is up again

```
Date: 2020-08-01 23:54:33
ID: 25
Error occured in: Global
Count: 1
Message: ..\AddOns\BigWigs\Loader.lua line 322:
   script ran too long
Debug:
   [string "@BigWigs\Loader.lua"]:322:
      BigWigs\Loader.lua:308
   [string "@BigWigs\Loader.lua"]:333:
      BigWigs\Loader.lua:328
   [string "@BigWigs\Loader.lua"]:345:
      BigWigs\Loader.lua:343
   [string "@BigWigs\Loader.lua"]:1291: ?()
   [string "@BigWigs\Loader.lua"]:1027:
      BigWigs\Loader.lua:1026
Locals:
obj = nil
index = 218
loaded = true
reason = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LittleWigs"
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "ADDON_LOADED"
(*temporary) = "script ran too long"
loadOnSlash = <table> {
}
next = <function> defined =[C]:-1
sysprint = <function> defined @Interface\AddOns\BigWigs\Loader.lua:304

```
the new file is

[BigWigsnew.log](https://github.com/BigWigsMods/BigWigs/files/5011702/BigWigsnew.log)

**Comment by elvador** [comment] 2020-08-02 09:25
Thanks. As you've already questioned: There is nothing wrong or unusual with your settings, I just wanted to double check.

In the end this whole topic comes down to how we load the modules. We do this on demand, so only when you enter an dungeon for the first time per login. 
At this point we'll have to rethink our current approach, as loading them all at the same time causes this freeze.

**Comment by elvador** [comment] 2020-08-02 23:22
After looking into the issue and gathering more info surrounding it:
* Our modules usually get loaded during the loading screen when zoning into a raid/dungeon. This causes the loading screen to be longer (which is the intended behavior)
* Loading the modules manually (by opening the corresponding freezes) also stutters/freezes the game, although they are generally shorter as there is nothing else being loaded at that time
* When zoning into visions, the event which is used to load our addon sometimes doesn't fire during the loading screen, resulting in a freeze right after you get out of it

@nebularg created a [pull request to split LittleWigs into an (ingame) addon per expansion](https://github.com/BigWigsMods/LittleWigs/pull/527). So instead of it fully loading all dungeons once you enter one, it'll only load the modules for this expansion. This should significantly reduce loading times.

If you want to try this, here is a packaged version of LittleWigs with this change implemented: [LittleWigs-v8.3.11-9-g23ca1ee7.zip](https://github.com/BigWigsMods/BigWigs/files/5013118/LittleWigs-v8.3.11-9-g23ca1ee7.1.zip)
For now you'll see a popup ingame about `LittleWigs_Cataclysm` being replaced by `LittleWigs` - this will of course be removed once the change is merged.

Any feedback is appreciated.

**Comment by milotic** [comment] 2020-08-03 01:19
done i going to test all night

**Comment by milotic** [comment] 2020-08-05 03:08
after tester where the lag happened in 2 days the lag and freezes are nearly gone example mouseover a world boss the lag down from 30 segs to 1 seg thanks this fix the problem

**Comment by funkydude** [comment] 2020-12-15 07:20
This has been fixed, thanks!

**Closed by funkydude** 2020-12-15 07:20 UTC
