### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'BigWigs' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.

### ISSUE THREAD

**Issue by ghost** [BigWigsMods/BigWigs#1353] opened 2023-02-20 19:02 UTC
## Describe the problem
When switching talents and entering combat Buggrabber intercepts the following error and pressing buttons is no longer possible.

### What steps will reproduce the problem?

1.  Switching talents as a rogue
2.  Entering combat with anything (mob, targetdummy, etc.)
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs 266 (d3260c4)

### Do you have an error log of what happened?
4x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@FrameXML/StanceBar.lua"]:25: in function `Update'
[string "@FrameXML/ActionBarController.lua"]:81: in function <FrameXML/ActionBarController.lua:55>

### Any additional information? (example: WoW language if not English)
Class Rogue, Bar-Addons: Bartender4 or Dominos, the error occurs for each one.
I have no macros with special code on any bars and i don't really understand what bigwigs wants to do with the actionbars.
I disabled every none essential bar in bartender or dominos and use the default blizzard ones for things like "extra action button".
With dominos the whole interface action of pressing a button fails and i can't use any buttons until i reload. The little clickable error box with a blocked addon appears. It has a disable or ignore button.
With bartender4 i can still use buttons but it feels a bit sloppy.

**Comment by ntowle** [comment] 2023-02-20 20:23
>  i don't really understand what bigwigs wants to do with the actionbars.

That's because BigWigs doesn't do anything with action bars. This is possibly being caused by some other addon. Try disabling all other addons and see if the issue occurs with only BigWigs.

**Comment by Sylux1992** [comment] 2023-02-20 20:58
I can't reproduce it with bigwigs alone but it also doesn't happen without bigwigs.

**Comment by funkydude** [comment] 2023-02-20 21:07
Then what we need you to do is enable a few addons at a time alongside BigWigs, maybe 2 or 3 depending on how many you have in total, until the issue happens. This way we can try and figure out what combination of addons is causing it.

**Comment by Sylux1992** [comment] 2023-02-20 21:15
Bigwigs + Bartender or Dominos

**Comment by funkydude** [comment] 2023-02-20 21:29
So you've disabled every addon other than BigWigs & Bartender and the issue occurs?
And it only occurs on your rogue character?

**Comment by Sylux1992** [comment] 2023-02-20 22:00
This was with just bigwigs+bartender and bugsack/buggrabber:

1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@FrameXML/StanceBar.lua"]:25: in function `Update'
[string "@FrameXML/ActionBarController.lua"]:81: in function <FrameXML/ActionBarController.lua:55>

I tried the same steps on my hunter, but it didn't happen at all

**Comment by Sylux1992** [comment] 2023-02-20 22:04
After switching talentloadouts and/or sometimes just switching 1 talentpoint around the error happens.

**Comment by funkydude** [comment] 2023-02-20 22:57
If you freshly log in, don't join a group or anything, just change your talents as the first thing you do, does it still occur?

**Comment by Sylux1992** [comment] 2023-02-20 23:02
it doesn't occur then

**Comment by funkydude** [comment] 2023-02-20 23:06
So this is only occurring when you're trying to change talents inside a group?

**Comment by Sylux1992** [comment] 2023-02-20 23:19
I tested it a bit more and i am fairly sure i know now how to reproduce it to 100%. being in or out of a group doesn't matter. I tested it being alone in valdrakken and opening my own group.

It occurs with these steps:
I log in, hit a mob, go ooc, switch talendloadout/taltents, hit a mob and try to open the talentwindow, it appears the "interface action failed because of an addon", now i switch talentloadout/talent again and reenter combat. The error happens.

I also tried just running around, stealthing, dragonriding, talking to npc's between the steps but once the interface action fails, the next combat after switching talents let's the error occur again. I have the feeling it's related to blizzards talent window/loadout management or something like that and a correlation of different things.

**Comment by funkydude** [comment] 2023-02-20 23:27
Open your World of Warcraft folder and navigate to `World of Warcraft\_retail_\Logs` and drag the "taint.log" file here to upload it.

**Comment by Sylux1992** [comment] 2023-02-20 23:53
I will do that tomorrow after work

**Comment by Sylux1992** [comment] 2023-02-21 19:41
Here is the taint log. Bartender+Bigwigs and Buggrabber/Bugsack
[taint.log](https://github.com/BigWigsMods/BigWigs/files/10797004/taint.log)

**Comment by funkydude** [comment] 2023-03-22 04:16
Sorry I forgot to reply to this @Sylux1992
Unfortunately your taint log is not detailed enough.
Please type this in chat: `/run SetCVar("taintLog", 2)`
Try to reproduce the issue and upload another taint log for us!

**Comment by Sylux1992** [comment] 2023-03-24 18:17
[taint.log](https://github.com/BigWigsMods/BigWigs/files/11065236/taint.log)
I reproduced the error a few time.
Here are the steps again:
Addons: Bigwigs, Bartender 4 and Buggrabber/Bugsack
Enter combat
Switch talent loadout
Enter Combat
Sometimes Optional: Try to open talent window while infight
Switch a talent/loadout
Enter combat
Error occurs

Next i try if it happens if all loadouts use the same actionbar configuration from blizzards talentinterface.

**Comment by Sylux1992** [comment] 2023-06-21 13:59
Bugsack still fetches the error when switching talents and reentering combat

**Comment by funkydude** [comment] 2023-06-21 14:19
Thanks! Could you also post a screenshot of your addons menu/list, showing the section with all the various BigWigs addons you are running?

**Comment by Sylux1992** [comment] 2023-06-21 19:20
![grafik](https://github.com/BigWigsMods/BigWigs/assets/123700981/919c5f41-abd9-4dd5-b63b-a780e3b6fca7)

**Comment by funkydude** [comment] 2023-06-21 20:57
Thanks, we are tracking this here in an effort to get Blizz to fix it: https://github.com/Stanzilla/WoWUIBugs/issues/447

No further input is needed from you, but when a fix is implemented, we will let you know and ask you to test again.

Thanks again for all your feedback!

**Comment by funkydude** [comment] 2024-06-12 20:05
Fixed in WoW 10.2.7

**Closed** 2024-06-12 20:05 UTC
Labels: retail
