### ISSUE TITLE
Request: Option to turn off nameplate icons & nameplate text

### ISSUE THREAD

**Issue by m-atlantis** [BigWigsMods/BigWigs#1797] opened 2024-09-04 23:47 UTC
## Describe the problem

Currently I have found no way to disable the nameplate plugin except for manually disabling it in the LUA file.

I believe an option to turn off nameplate icons, and nameplate text as separate options would be a great QoL.

**Comment by funkydude** [comment] 2024-09-04 23:49
Duplicate of #1784

**Closed by funkydude** 2024-09-04 23:49 UTC
Labels: retail
