### ISSUE TITLE
Feature Request: Option to disable all nameplate icons

### ISSUE THREAD

**Issue by RichBj** [BigWigsMods/BigWigs#1764] opened 2024-08-24 16:34 UTC
## Describe the problem
Currently there is no way to easily disable all nameplate icons. The only way to do this is to go into each ability of every trash mob and boss and turn it off. I am asking if it is possible to make an option to disable all nameplate icons from within the Nameplates setting tab.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs version 355

**Comment by funkydude** [comment] 2024-08-24 16:44
Duplicate of #1760

**Closed** 2024-08-24 16:44 UTC
Labels: retail
